/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a dbus/connmanagent -c ConnmanAgent agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbus/connmanagent.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ConnmanAgent
 */

ConnmanAgent::ConnmanAgent(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ConnmanAgent::~ConnmanAgent()
{
    // destructor
}

void ConnmanAgent::Cancel()
{
    // handle method call net.connman.Agent.Cancel
    QMetaObject::invokeMethod(parent(), "Cancel");
}

void ConnmanAgent::Release()
{
    // handle method call net.connman.Agent.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

void ConnmanAgent::ReportError(const QDBusObjectPath &in0, const QString &in1)
{
    // handle method call net.connman.Agent.ReportError
    QMetaObject::invokeMethod(parent(), "ReportError", Q_ARG(QDBusObjectPath, in0), Q_ARG(QString, in1));
}

QVariantMap ConnmanAgent::RequestInput(const QDBusObjectPath &in0, const QVariantMap &in1)
{
    // handle method call net.connman.Agent.RequestInput
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "RequestInput", Q_RETURN_ARG(QVariantMap, out0), Q_ARG(QDBusObjectPath, in0), Q_ARG(QVariantMap, in1));
    return out0;
}

